### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by spunkyblob** [The-300lb-Gorilla/Ender-2-Pro-BTT-V3#2]
Thanks for your tips on the bed levelling and for compiling this firmware. I am using it now with no issues. I do see however, that you have updated the firmware 6 hours ago.

Also, quick side note...as we seem to be like minded with pushing the ender 2 pro. I was thinking of purchasing the official creality sprite extruder that is used on the s1. I'm convinced it will work and I wont have any issues, but can you foresee any problems?

Thanks

**Comment by The-300lb-Gorilla** [comment]
Yes, the firmware I dropped last night is updated, You should grab the latest copy and update, and it has fixed a bug with the Manual Bed Leveling (Tramming) system. On occasion it would jam the stepper motors. I fixed the code so that cannot happen again. Also, I have updated the TFT35 E3v3 Touch Screen firmware so it is Ender 2 Pro Specific. Configured for the Ender 2 Pro Only. Should you decide to get one. (Less than $45USD on Amazon, V3.0.1 is what I have.)
Stay away from the sprite. I had one, and it was a total waste of money. I just sold my S1 and my CR-6SE. I hated those printers. My thought is when it comes to 3D Printers, is that simple is always better. If you are looking for a high temp hot end, and this is for the Ender 2 Pro, I got 2 Gulf Coast Robotics All Metal Hot Ends for both my Ender 2 Pros. They did a full redesign, and it is better than the version 1. I tried a MicroSwiss All Metal Hot End that was sent to me, and I had issues with clogging and the design is not as good as the Gulf Coast Robotics one. This one is Just my opinion mind you.

**Comment by spunkyblob** [comment]
Yeah, I have the microswiss on my 3 v2 and it's terrible. Always having issues with it.

My only other upgrade is going to be to add a cr touch to the the pro 2. Will your firmware work with the touch or will I need to recompile it with different settings? I don't mind looking into this if this is the case.

Thanks for your help,

Tom

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by The-300lb-Gorilla** [comment]
The firmware I configured is NOT for a BL/CR Touch. The Ender 2 Pro has such a small bed that it takes forever for a ABL probe to run the grid, I can do it faster with Manual Mesh Bed Leveling. Last time I had a CR Touch configured on my Ender 2 Pro, it crushed the probe and snapped the probe mount right off. Watch this video:
https://youtu.be/F8g1s3Supxs
Then ask yourself, is it really worth it. I did not configure the firmware for this CR-Touch that was crushed. Someone else did.
I was being lazy, and figured it would save me time, Yeah, costly lesson.
I can configure a copy of BTT-SKR-Mini-E3-v3 firmware for a CR-Touch, BUT...... Since mine was crushed, I would have no way to test it, unless you want to be the test subject. :-) Up to you. 
I have released the 2 final versions for the BTT-SKR-Mini-E3 - v2 & v3

**Comment by The-300lb-Gorilla** [comment]
![Shattered CR-Touch Probe](https://user-images.githubusercontent.com/107377482/175821644-5b3fca8b-9cc8-4a53-8210-37409420e5fd.jpg)

**Comment by The-300lb-Gorilla** [comment]
as you can see. CRUNCH!
I should have done it myself.

**Comment by The-300lb-Gorilla** [comment]
![Wrote The Books On Converting and Ender 2 Pro](https://user-images.githubusercontent.com/107377482/175821774-a4b19ba1-8a40-4176-9a0b-9a4f61ef8cb4.jpg)

**Comment by The-300lb-Gorilla** [comment]
As you can see from the picture above. I Literally wrote the book on converting an Ender 2 Pro to the BTT-SKR-MINI-E3 v2 + v3.
I document all my code. I am in the process of documenting my work on the firmware for the TFT35-E3-v3.0.1.

**Comment by The-300lb-Gorilla** [comment]
Oh, almost forgot, if you put a all metal hot end on an ender 2 pro, you may want to upgrade the cooling fan from 40mm to 50mm. It keeps things in the hot end area cooler, and you can print the upgrade bracket from PLA, not PETG or ABS. I also added a second parts cooling fan with a wide nozzle to cool most of the part as the other fan cools directly at the extrusion point. It took some doing, but I designed this for optimum cooling of the hot end.
![Left View](https://user-images.githubusercontent.com/107377482/175822638-f8b5ec65-968c-42f5-8060-00a69f1f641e.jpg)
![Right View](https://user-images.githubusercontent.com/107377482/175822646-da5bd982-6d8b-46db-9ebb-636caf504fdb.jpg)

**Comment by The-300lb-Gorilla** [comment]
Hey Tom,
I should have a working copy of the BTT-SKR-Mini-E3-v3 CR/BL-Touch done by Tuesday night-ish my time. EST USA

**Comment by The-300lb-Gorilla** [comment]
![Nozzle to Probe tip offset](https://user-images.githubusercontent.com/107377482/175840185-7f988806-0bfd-4d3c-a6b6-866c2750b820.jpg)
I need to know the offset of the center of the probe tip to the tip of the nozzle.
Use the picture above for reference. Without this information, I cannot complete the coding and firmware compile.

**Comment by The-300lb-Gorilla** [comment]
Scratch that, I cannot even run a compile without a probe on my machine to test the feed_rate_mm_s.
Looks like you will have to do this one on your own. Sorry
